# Generated by Django 2.2 on 2019-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
