# Generated by Django 2.2 on 2019-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191216_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.TextField(),
        ),
    ]
