# Generated by Django 2.2 on 2019-12-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191216_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
