# Generated by Django 2.2 on 2019-12-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20191216_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skills_required',
            new_name='required_skills',
        ),
    ]
